[workspace]
members = [
    "crates/helio-core",
    "crates/helio-render",
    "crates/helio-lighting",
    "crates/examples",
]
resolver = "2"

[workspace.dependencies]
blade-graphics = { git = "https://github.com/kvark/blade" }
blade-macros = { git = "https://github.com/kvark/blade" }
bytemuck = { version = "1", features = ["derive"] }
glam = { version = "0.29", features = ["bytemuck"] }
winit = "0.30"
env_logger = "0.11"
log = "0.4"
