[workspace]
members = [
    "crates/helio-core",
    "crates/helio-render",
    "crates/helio-render-v2",
    "crates/helio-lighting",
    "crates/helio-features",
    "crates/helio-feature-base-geometry",
    "crates/helio-feature-lighting",
    "crates/helio-feature-materials",
    "crates/helio-feature-procedural-shadows",
    "crates/helio-feature-bloom",
    "crates/helio-feature-billboards",
    "crates/examples",
]
resolver = "2"

[workspace.dependencies]
blade-graphics = { git = "https://github.com/tristanpoland/blade", rev = "d85bd14a78ed7729abc298906e87332257674a02" }
blade-macros =   { git = "https://github.com/tristanpoland/blade", rev = "d85bd14a78ed7729abc298906e87332257674a02" }
bytemuck = { version = "1", features = ["derive"] }
glam = { version = "0.29", features = ["bytemuck"] }
winit = "0.30.12"
env_logger = "0.11"
log = "0.4"