[package]
name = "helio-feature-materials"
version = "0.1.0"
edition = "2021"

[dependencies]
helio-features = { path = "../helio-features" }
blade-graphics = { workspace = true }
blade-macros = { workspace = true }
glam = { workspace = true }
bytemuck = { workspace = true }
log = "0.4"