[package]
name = "helio-feature-base-geometry"
version = "0.1.0"
edition = "2021"

[dependencies]
helio-core = { path = "../helio-core" }
helio-features = { path = "../helio-features" }
blade-graphics = { workspace = true }
glam = { workspace = true }
log = "0.4"