[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "basic_rendering"
path = "basic_rendering.rs"

[[bin]]
name = "minimal_rendering"
path = "minimal_rendering.rs"

[[bin]]
name = "feature_showcase"
path = "feature_showcase.rs"

[[bin]]
name = "forward_with_gi"
path = "forward_with_gi.rs"

[dependencies]
helio-core = { path = "../helio-core" }
helio-render = { path = "../helio-render" }
helio-lighting = { path = "../helio-lighting" }
helio-features = { path = "../helio-features" }
helio-feature-forward-lighting = { path = "../helio-feature-forward-lighting" }
blade-graphics = { workspace = true }
blade-macros = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
winit = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
