[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "basic_rendering"
path = "basic_rendering.rs"

[dependencies]
helio-core = { path = "../helio-core" }
helio-render = { path = "../helio-render" }
blade-graphics = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
winit = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
