[package]
name = "helio-example"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "basic_rendering"
path = "basic_rendering.rs"

[dependencies]
helio-core = { path = "../helio-core" }
helio-render = { path = "../helio-render" }
helio-lighting = { path = "../helio-lighting" }
helio-material = { path = "../helio-material" }
helio-postprocess = { path = "../helio-postprocess" }
blade-graphics = { workspace = true }
blade-macros = { workspace = true }
glam = { workspace = true }
bytemuck = { workspace = true }
winit = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
