[package]
name = "helio-features"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { workspace = true }
glam = { workspace = true }
log = { workspace = true }
bytemuck = { workspace = true }
